import "./globals.css"
import { fontsSans } from "./fonts"
import { Metadata } from "next"
import { Providers } from "./providers"

const fontFamily = fontsSans.map((font) => font.style.fontFamily).join(",")

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: { width: "device-width", initialScale: 1 },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: fontFamily }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
