# .github/workflows/nextjs-build-and-deploy.yml

name: GitHub Pages deploy
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22 LTS (lts/jod)
        uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          cache: "npm"
      - name: Installing my packages
        run: npm ci
      - name: Build my App
        # Suppress Jekyll not serving the _next folder
        run: |
          npm run build
          # npm run export
          touch ./out/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy to.
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
